#!/bin/bash
echo "To check Netlify function logs for errors:"
echo ""
echo "1. Install Netlify CLI (if not already):"
echo "   npm install -g netlify-cli"
echo ""
echo "2. Login and link:"
echo "   netlify login"
echo "   netlify link"
echo ""
echo "3. View logs:"
echo "   netlify functions:log upload"
echo ""
echo "Or check in dashboard:"
echo "   Netlify → Functions → upload → Invocation log"
